Move check for role session to the code path that actually assumes the role
The change in behaviour is from:

    assume-role --role <role-arn> assume-role --role <role-arn> ls
    ERROR: --role-session-name is mandatory when the current principal is a role

to

    $ assume-role --role <role-arn> assume-role --role <role-arn> ls
    main.tf

And the reason is to avoid requiring a session name for invocations
that only use cached credentials without actually requiring an AWS
API call.